#' Run MEGSA
#'
#' Identifies mutually exclusive gene sets from a binary mutation matrix.
#'
#' @param mutationMat A logical or numeric matrix with samples in rows and
#'   genes in columns. Non-zero numeric values are treated as mutations.
#' @param maxSSimu Optional null-distribution matrix generated by
#'   [funMaxSSimu()]. Rows are simulations and columns correspond to gene-set
#'   sizes 2 through `maxSize`.
#' @param nSimu Number of simulations to run when `maxSSimu` is not supplied.
#' @param nPairStart Number of starting gene pairs for the forward search.
#' @param maxSize Maximum size of a mutually exclusive gene set.
#' @param level Family-wise error rate threshold.
#' @param detail If `TRUE`, print progress messages.
#' @param search Search strategy. `"screened"` uses the 2016 correlation
#'   screening heuristic; `"exhaustive"` evaluates all candidate pairs and
#'   additions as in the earlier script release.
#' @param ncores Number of parallel worker processes for simulations.
#' @param seed Optional random seed for simulation reproducibility.
#' @param resultTableFile Optional output path for a tab-delimited MEGS table.
#' @param figureDir Optional output directory for MEGS plots.
#' @param type Figure file type: `"pdf"`, `"png"`, or `"jpg"`.
#'
#' @return A list with global p-value `p` and significant mutually exclusive
#'   gene sets in `MEGSList`.
#'
#' @references Hua X, Hyland PL, Huang J, Song L, Zhu B, Caporaso NE,
#'   Landi MT, Chatterjee N, Shi J. 2016. MEGSA: A powerful and flexible
#'   framework for analyzing mutual exclusivity of tumor mutations. *The
#'   American Journal of Human Genetics* 98(3):442-455.
#'   <https://doi.org/10.1016/j.ajhg.2015.12.021>
#'
#' @export
megsa <- function(mutationMat, maxSSimu = NULL, nSimu = 1000,
                  nPairStart = 10, maxSize = 6, level = 0.05,
                  detail = FALSE, search = c("screened", "exhaustive"),
                  ncores = 1, seed = NULL, resultTableFile = NULL,
                  figureDir = NULL, type = "pdf") {
  mutationMat <- normalize_mutation_matrix(mutationMat)
  maxSSimu <- normalize_max_simu_matrix(maxSSimu)
  result <- funSelect(
    mutationMat = mutationMat,
    maxSSimu = maxSSimu,
    nSimu = nSimu,
    nPairStart = nPairStart,
    maxSize = maxSize,
    level = level,
    detail = detail,
    search = search,
    ncores = ncores,
    seed = seed
  )

  if (!is.null(resultTableFile)) {
    funPrintMEGS(result$MEGSList, outputFile = resultTableFile)
  }
  if (!is.null(figureDir)) {
    funPlotMEGS(result$MEGSList, mutationMat, outputDir = figureDir, type = type)
  }

  structure(result, class = c("megsa", class(result)))
}

#' Run MEGSA from files
#'
#' @inheritParams megsa
#' @param mutationMatFile Path to a tab-delimited mutation matrix. The first
#'   row contains gene names and the first column contains sample IDs.
#' @param maxSSimuFile Optional path to a tab-delimited null-distribution
#'   matrix.
#'
#' @return A MEGSA result object.
#'
#' @export
megsa_file <- function(mutationMatFile, maxSSimuFile = NULL, nSimu = 1000,
                       nPairStart = 10, maxSize = 6, level = 0.05,
                       detail = FALSE, search = c("screened", "exhaustive"),
                       ncores = 1, seed = NULL, resultTableFile = NULL,
                       figureDir = NULL, type = "pdf") {
  mutationMat <- read_megsa_mutation_matrix(mutationMatFile)
  maxSSimu <- if (is.null(maxSSimuFile)) {
    NULL
  } else {
    read_megsa_max_simu(maxSSimuFile)
  }

  megsa(
    mutationMat = mutationMat,
    maxSSimu = maxSSimu,
    nSimu = nSimu,
    nPairStart = nPairStart,
    maxSize = maxSize,
    level = level,
    detail = detail,
    search = search,
    ncores = ncores,
    seed = seed,
    resultTableFile = resultTableFile,
    figureDir = figureDir,
    type = type
  )
}

#' Read MEGSA example-style input files
#'
#' @param file Path to a tab-delimited input file.
#'
#' @return `read_megsa_mutation_matrix()` returns a logical mutation matrix.
#'   `read_megsa_max_simu()` returns a numeric simulation matrix.
#'
#' @name read_megsa_files
NULL

#' @rdname read_megsa_files
#' @export
read_megsa_mutation_matrix <- function(file) {
  normalize_mutation_matrix(utils::read.table(file, header = TRUE, row.names = 1) != 0)
}

#' @rdname read_megsa_files
#' @export
read_megsa_max_simu <- function(file) {
  normalize_max_simu_matrix(utils::read.table(file))
}

#' @export
print.megsa <- function(x, ...) {
  cat("MEGSA result\n")
  cat("  Global p-value:", format(x$p), "\n")
  cat("  Significant MEGS:", length(x$MEGSList), "\n")
  invisible(x)
}

#' @export
as.data.frame.megsa <- function(x, row.names = NULL, optional = FALSE, ...) {
  funPrintMEGS(x$MEGSList)
}

#' Generate a mutation matrix
#'
#' Simulates mutation data under an independent null model (`"H0"`) or a
#' mutually exclusive alternative model (`"H1"`). This is the package version
#' of the simulation helper used in the historical workspace scripts.
#'
#' @param N Number of samples.
#' @param M Number of genes.
#' @param parList Model parameters. Use `pi` for `"H0"` and `gamma`/`delta`
#'   for `"H1"`.
#' @param hypothesis Either `"H0"` or `"H1"`.
#'
#' @return A logical mutation matrix.
#'
#' @export
simulate_mutation_matrix <- function(N, M, parList, hypothesis = c("H0", "H1")) {
  hypothesis <- match.arg(hypothesis)
  validate_positive_integer(N, "N")
  validate_positive_integer(M, "M")

  mutationMat <- matrix(FALSE, N, M)
  if (hypothesis == "H0") {
    pi <- parList$pi
    if (length(pi) == 1) {
      mutationMat[stats::runif(N * M) < pi] <- TRUE
    } else if (length(pi) == M) {
      mutationMat[stats::runif(N * M) < rep(pi, each = N)] <- TRUE
    } else {
      stop("Invalid value of pi.", call. = FALSE)
    }
  } else {
    gamma <- parList$gamma
    delta <- parList$delta
    if (length(delta) == 1) {
      mutationMat[stats::runif(N * M) < delta] <- TRUE
    } else if (length(delta) == M) {
      mutationMat[stats::runif(N * M) < rep(delta, each = N)] <- TRUE
    } else {
      stop("Invalid value of delta.", call. = FALSE)
    }
    exclusiveRows <- stats::runif(N) < gamma
    nExclusive <- sum(exclusiveRows)
    exclusiveMat <- matrix(FALSE, nExclusive, M)
    if (nExclusive > 0) {
      if (length(delta) == 1) {
        geneIndex <- sample.int(M, nExclusive, replace = TRUE)
      } else {
        geneIndex <- sample.int(M, nExclusive, replace = TRUE, prob = delta / sum(delta))
      }
      exclusiveMat[cbind(seq_len(nExclusive), geneIndex)] <- TRUE
      mutationMat[exclusiveRows, ] <- mutationMat[exclusiveRows, , drop = FALSE] | exclusiveMat
    }
  }

  dimnames(mutationMat) <- list(paste0("P", seq_len(N)), paste0("G", seq_len(M)))
  mutationMat
}

#' @rdname simulate_mutation_matrix
#' @export
funGenerateData <- simulate_mutation_matrix

#' Estimate MEGSA model parameters
#'
#' @inheritParams megsa
#' @param parVec Parameter vector used internally by the likelihood functions.
#' @param q Optional count vector indexed by the number of mutations in a row.
#' @param tol Optimizer boundary tolerance.
#'
#' @return A numeric value for likelihood helpers, or a list of parameter
#'   estimates and likelihood ratio statistic for [funEstimate()].
#'
#' @name megsa_model
NULL

#' @rdname megsa_model
#' @export
funLogLikelihood <- function(parVec, mutationMat, q = NULL) {
  mutationMat <- normalize_mutation_matrix(mutationMat, min_cols = 1)
  gamma <- parVec[1]
  delta <- parVec[-1]
  M <- ncol(mutationMat)
  if (is.null(q)) {
    q <- as.vector(table(factor(rowSums(mutationMat), levels = 0:M)))
  }

  if (length(delta) == 1) {
    J <- seq_len(M)
    logL <- M * q[1] * log(1 - delta) + q[1] * log(1 - gamma) +
      sum(q[-1] * (
        log(J / M) + (J - 1) * log(delta) + (M - J) * log(1 - delta) +
          log(M / J * delta * (1 - gamma) + gamma)
      ))
  } else if (length(delta) == M) {
    tempA <- mutation_patterns(M)
    tempProbMat <- matrix(rep(delta, each = 2^M), 2^M, M)
    tempProbMat[!tempA] <- 1 - tempProbMat[!tempA]
    tempProd <- apply(tempProbMat, 1, prod)
    tempMat <- rep(delta / sum(delta), each = 2^M) * tempA * (tempProd / tempProbMat)
    tempProb <- (1 - gamma) * tempProd + gamma * rowSums(tempMat)
    prob <- tempProb[row_pattern_index(mutationMat)]
    logL <- sum(log(prob))
  } else {
    stop("Invalid value of delta.", call. = FALSE)
  }

  -logL
}

#' @rdname megsa_model
#' @export
funGradient <- function(parVec, mutationMat, q = NULL) {
  mutationMat <- normalize_mutation_matrix(mutationMat, min_cols = 1)
  gamma <- parVec[1]
  delta <- parVec[-1]
  M <- ncol(mutationMat)
  if (is.null(q)) {
    q <- as.vector(table(factor(rowSums(mutationMat), levels = 0:M)))
  }
  if (length(delta) == 1) {
    delta <- rep(delta, M)
  }
  if (length(delta) != M) {
    stop("Invalid value of delta.", call. = FALSE)
  }

  sumDelta <- sum(delta)
  tempA <- mutation_patterns(M)
  tempProbMat1 <- tempProbMat2 <- matrix(delta, 2^M, M, byrow = TRUE)
  tempProbMat2[!tempA] <- 1 - tempProbMat1[!tempA]
  temp1 <- apply(tempProbMat2, 1, prod)
  temp2 <- temp1 / tempProbMat2
  tempProbMat3 <- tempProbMat1 / sumDelta * tempA * temp2
  temp3 <- rowSums(tempProbMat3)
  tempProb <- (1 - gamma) * temp1 + gamma * temp3
  tempGradGamma <- (temp3 - temp1) / tempProb
  tempGradMat <- matrix(NA_real_, 2^M, M)
  temp4 <- (1 - gamma) * (tempA * 2 - 1) * temp2
  temp5 <- (sumDelta - delta) / sumDelta^2
  temp6 <- rep(temp5, each = 2^M) * tempA * temp2
  for (i in seq_len(M)) {
    temp7 <- -tempProbMat1[, -i, drop = FALSE] / sumDelta^2 *
      tempA[, -i, drop = FALSE] * temp2[, -i, drop = FALSE] +
      tempProbMat1[, -i, drop = FALSE] / sumDelta *
        tempA[, -i, drop = FALSE] *
        (temp2[, -i, drop = FALSE] / tempProbMat2[, i] * (tempA[, i] * 2 - 1))
    tempGradMat[, i] <- temp4[, i] + gamma * (temp6[, i] + rowSums(temp7))
  }
  tempGradMat <- tempGradMat / tempProb
  tempIdx <- row_pattern_index(mutationMat)
  grad <- c(sum(tempGradGamma[tempIdx]), colSums(tempGradMat[tempIdx, , drop = FALSE]))

  -grad
}

#' @rdname megsa_model
#' @export
funEstimate <- function(mutationMat, tol = 1e-7) {
  mutationMat <- normalize_mutation_matrix(mutationMat, min_cols = 1)
  context <- estimate_context(mutationMat)
  M <- context$M
  tempRowSums <- context$row_sums
  piHat <- context$pi
  logL0 <- context$logL0

  tempOptim <- NULL
  for (eps in 10^(-((-log10(tol)):3))) {
    start <- c(mean(tempRowSums > 0), piHat)
    start <- pmin(pmax(start, eps), 1 - eps)
    tempOptim <- try(
      stats::optim(
        start,
        context_log_likelihood,
        gr = context_gradient,
        method = "L-BFGS-B",
        lower = c(0, rep(eps, M)),
        upper = rep(1 - eps, M + 1),
        context = context
      ),
      silent = TRUE
    )
    if (is.list(tempOptim) &&
        identical(tempOptim$convergence, 0L) &&
        all(tempOptim$par > 0) &&
        all(tempOptim$par < 1)) {
      break
    }
  }

  if (!is.list(tempOptim) || !identical(tempOptim$convergence, 0L)) {
    stop("ERROR in OPTIM FUNCTION.", call. = FALSE)
  }

  logL1 <- -tempOptim$value
  gammaHat <- tempOptim$par[1]
  deltaHat <- tempOptim$par[-1]
  if (logL1 < logL0) {
    gammaHat <- 0
    deltaHat <- piHat
    logL1 <- logL0
  }
  S <- -2 * (logL0 - logL1)

  list(pi = piHat, gamma = gammaHat, delta = deltaHat, logL0 = logL0, logL1 = logL1, S = S)
}

#' Search and test MEGSA gene sets
#'
#' @inheritParams megsa
#' @param geneStart Character vector of starting gene names.
#' @param geneStartList List of gene sets used internally by the selection
#'   procedure.
#' @param eps Tolerance used when comparing q-values during model selection.
#' @param nPerm Number of local permutations for add/drop decisions.
#' @param permResult Cached permutation results used internally.
#' @param corMat Optional precomputed correlation matrix used internally by
#'   the screened search strategy.
#'
#' @return Search/test functions return lists or matrices matching the
#'   historical MEGSA script outputs.
#'
#' @name megsa_search
NULL

#' @rdname megsa_search
#' @export
funAdd1 <- function(geneStart, mutationMat, detail = TRUE,
                    search = c("screened", "exhaustive"), corMat = NULL) {
  search <- match.arg(search)
  mutationMat <- normalize_mutation_matrix(mutationMat)
  geneAll <- colnames(mutationMat)
  M0 <- length(geneStart)
  if (M0 < 1) {
    stop("Must start from at least one gene.", call. = FALSE)
  }
  if (any(!geneStart %in% geneAll)) {
    stop("Invalid gene names.", call. = FALSE)
  }

  geneCandidate <- geneAll[!geneAll %in% geneStart]
  M1 <- length(geneCandidate)
  if (M1 < 1) {
    stop("Candidate gene set must have at least one gene outside the start set.", call. = FALSE)
  }

  tempOrder <- candidate_add_order(mutationMat, geneStart, geneCandidate, search, corMat = corMat)
  S <- rep(NA_real_, M1)
  for (i in tempOrder) {
    S[i] <- funEstimate(mutationMat[, c(geneStart, geneCandidate[i]), drop = FALSE])$S
    if (detail) {
      cat(i, "\t", geneStart, "+", geneCandidate[i], S[i], "\n")
    }
  }

  tempIdx <- which.max(S)
  list(gene = c(geneStart, geneCandidate[tempIdx]), S = S[tempIdx])
}

#' @rdname megsa_search
#' @export
funMaxS <- function(mutationMat, nPairStart = 10, maxSize = 6, detail = TRUE,
                    search = c("screened", "exhaustive")) {
  search <- match.arg(search)
  mutationMat <- normalize_mutation_matrix(mutationMat)
  validate_positive_integer(nPairStart, "nPairStart")
  validate_positive_integer(maxSize, "maxSize")

  geneAll <- colnames(mutationMat)
  M <- ncol(mutationMat)
  maxSize <- min(maxSize, M)
  tempCombn <- utils::combn(M, 2)
  nPair <- ncol(tempCombn)
  nPairStart <- min(nPairStart, nPair)
  pairS <- rep(NA_real_, nPair)
  names(pairS) <- seq_len(nPair)
  corMat <- if (search == "screened") safe_cor(mutationMat) else NULL

  for (i in candidate_pair_order(mutationMat, nPairStart, search, corMat = corMat)) {
    pairS[i] <- funEstimate(mutationMat[, tempCombn[, i], drop = FALSE])$S
    if (detail) {
      cat(i, "\t", geneAll[tempCombn[, i]], pairS[i], "\n")
    }
  }

  startIdx <- order(pairS, decreasing = TRUE, na.last = NA)[seq_len(nPairStart)]
  startPairS <- pairS[startIdx]
  startCombn <- tempCombn[, as.integer(names(startPairS)), drop = FALSE]
  maxSMat <- matrix(
    NA_real_,
    nPairStart,
    maxSize - 1,
    dimnames = list(seq_len(nPairStart), 2:maxSize)
  )
  geneMat <- matrix(
    NA_character_,
    nPairStart,
    maxSize,
    dimnames = list(seq_len(nPairStart), seq_len(maxSize))
  )
  maxSMat[, "2"] <- startPairS
  geneMat[, "1"] <- geneAll[startCombn[1, ]]
  geneMat[, "2"] <- geneAll[startCombn[2, ]]

  if (maxSize > 2) {
    for (i in seq_len(nPairStart)) {
      tempGeneSet <- geneAll[startCombn[, i]]
      for (j in seq.int(2, maxSize - 1)) {
        tempAdd <- funAdd1(
          tempGeneSet,
          mutationMat,
          detail = detail,
          search = search,
          corMat = corMat
        )
        tempGeneSet <- tempAdd$gene
        maxSMat[i, j] <- tempAdd$S
        geneMat[i, j + 1] <- tempGeneSet[j + 1]
      }
    }
  }

  list(maxSMat = maxSMat, geneMat = geneMat, startCombn = startCombn, startPairS = startPairS)
}

#' @rdname megsa_search
#' @export
funMaxSSimu <- function(mutationMat, nSimu = 1000, nPairStart = 10,
                        maxSize = 6, detail = TRUE,
                        search = c("screened", "exhaustive"),
                        ncores = 1, seed = NULL) {
  search <- match.arg(search)
  mutationMat <- normalize_mutation_matrix(mutationMat)
  validate_positive_integer(nSimu, "nSimu")
  validate_positive_integer(ncores, "ncores")

  N <- nrow(mutationMat)
  M <- ncol(mutationMat)
  ncores <- min(ncores, nSimu)

  simulate_one <- function(s) {
    permutationMat <- mutationMat
    for (j in seq_len(M)) {
      permutationMat[, j] <- mutationMat[sample.int(N), j]
    }
    maxSMat <- funMaxS(
      permutationMat,
      nPairStart = nPairStart,
      maxSize = maxSize,
      detail = detail,
      search = search
    )$maxSMat
    if (detail) {
      cat("Simulation", s, "done", "\n")
    }
    maxSMat
  }

  if (ncores == 1) {
    if (!is.null(seed)) {
      set.seed(seed)
    }
    maxSMats <- lapply(seq_len(nSimu), simulate_one)
  } else {
    cl <- parallel::makeCluster(ncores)
    on.exit(parallel::stopCluster(cl), add = TRUE)
    parallel::clusterExport(
      cl,
      varlist = c(
        "funMaxS", "funAdd1", "funEstimate", "funLogLikelihood",
        "funGradient", "normalize_mutation_matrix", "candidate_pair_order",
        "candidate_add_order", "safe_cor", "mutation_patterns",
        "row_pattern_index", "estimate_context", "context_log_likelihood",
        "context_gradient", "validate_positive_integer"
      ),
      envir = parent.env(environment())
    )
    if (!is.null(seed)) {
      parallel::clusterSetRNGStream(cl, seed)
    }
    maxSMats <- parallel::parLapply(cl, seq_len(nSimu), simulate_one)
  }

  maxSArray <- simplify2array(maxSMats)
  maxSSimu <- apply(maxSArray, c(3, 2), max)
  normalize_max_simu_matrix(maxSSimu)
}

#' @rdname megsa_search
#' @export
funGlobalTest <- function(mutationMat, maxSSimu = NULL, nSimu = 1000,
                          nPairStart = 10, maxSize = 6, detail = TRUE,
                          search = c("screened", "exhaustive"),
                          ncores = 1, seed = NULL) {
  search <- match.arg(search)
  mutationMat <- normalize_mutation_matrix(mutationMat)
  maxSSimu <- normalize_max_simu_matrix(maxSSimu)

  if (!is.null(maxSSimu)) {
    nSimu <- nrow(maxSSimu)
    maxSize <- ncol(maxSSimu) + 1
  } else {
    maxSSimu <- funMaxSSimu(
      mutationMat,
      nSimu = nSimu,
      nPairStart = nPairStart,
      maxSize = maxSize,
      detail = detail,
      search = search,
      ncores = ncores,
      seed = seed
    )
  }

  resultReal <- funMaxS(
    mutationMat,
    nPairStart = nPairStart,
    maxSize = maxSize,
    detail = detail,
    search = search
  )
  maxSMatReal <- resultReal$maxSMat
  maxSReal <- apply(maxSMatReal, 2, max)
  rankMat <- apply(-rbind(maxSReal, maxSSimu), 2, rank, ties.method = "max")
  if (is.null(dim(rankMat))) {
    rankMat <- matrix(rankMat, ncol = 1)
  }
  minRankVecReal <- min(rankMat[1, ] - 1)
  simuRankMat <- apply(-maxSSimu, 2, rank, ties.method = "max")
  if (is.null(dim(simuRankMat))) {
    simuRankMat <- matrix(simuRankMat, ncol = 1)
  }
  minRankVecSimu <- apply(simuRankMat, 1, min)
  p <- mean(minRankVecSimu <= minRankVecReal)

  list(
    p = p,
    q = minRankVecSimu / nSimu,
    maxSReal = maxSReal,
    maxSSimu = maxSSimu,
    startPairIdx = resultReal$startCombn,
    startPairS = resultReal$startPairS
  )
}

#' @rdname megsa_search
#' @export
funAdd1RealData <- function(geneStartList, mutationMat, maxSSimu,
                            eps = 0.005, level = 0.05, nPerm = 1e2,
                            detail = TRUE) {
  mutationMat <- normalize_mutation_matrix(mutationMat)
  maxSSimu <- normalize_max_simu_matrix(maxSSimu)
  maxSize <- ncol(maxSSimu) + 1
  geneAll <- colnames(mutationMat)
  N <- nrow(mutationMat)
  geneEndList <- list()
  k <- 1

  for (i in seq_along(geneStartList)) {
    geneStart <- geneStartList[[i]]
    n0 <- length(geneStart)
    if (is.null(attr(geneStart, "S")) || is.null(attr(geneStart, "q"))) {
      tempS <- funEstimate(mutationMat[, geneStart, drop = FALSE])$S
      tempQ <- mean(maxSSimu[, n0 - 1] >= tempS)
      attr(geneStart, "S") <- tempS
      attr(geneStart, "q") <- tempQ
    }
    if (n0 == maxSize) {
      attr(geneStart, "change") <- FALSE
    }
    if (!is.null(attr(geneStart, "change")) && !attr(geneStart, "change")) {
      geneEndList[[k]] <- geneStart
      k <- k + 1
      next
    }

    S0 <- attr(geneStart, "S")
    q0 <- attr(geneStart, "q")
    geneCandidate <- geneAll[!geneAll %in% geneStart]
    n1 <- length(geneCandidate)
    S1Vec <- q1Vec <- rep(NA_real_, n1)
    for (j in seq_len(n1)) {
      S1Vec[j] <- funEstimate(mutationMat[, c(geneStart, geneCandidate[j]), drop = FALSE])$S
      q1Vec[j] <- mean(maxSSimu[, n0] >= S1Vec[j])
      if (detail) {
        cat(i, j, geneStart, S0, q0, "+", geneCandidate[j], S1Vec[j], q1Vec[j], "\n")
      }
    }

    tempIdx1 <- which(abs(q1Vec - q0) < eps)
    tempIdx2 <- which(q1Vec <= q0 - eps)
    if (length(tempIdx1) > 0) {
      maxSPermVec <- rep(NA_real_, nPerm)
      for (ii in seq_len(nPerm)) {
        tempPermIdx <- sample.int(N)
        SPerm <- rep(NA_real_, n1)
        for (jj in seq_len(n1)) {
          APerm <- mutationMat[, c(geneStart, geneCandidate[jj]), drop = FALSE]
          APerm[, n0 + 1] <- APerm[tempPermIdx, n0 + 1]
          SPerm[jj] <- funEstimate(APerm)$S
        }
        maxSPermVec[ii] <- max(SPerm)
        pMin <- mean(maxSPermVec >= max(S1Vec[tempIdx1]), na.rm = TRUE)
        if (ii >= nPerm / 5 && pMin > 2 * level) {
          break
        }
      }
      pVec <- vapply(tempIdx1, function(ii) {
        mean(maxSPermVec >= S1Vec[ii], na.rm = TRUE)
      }, numeric(1))
      tempIdx2 <- sort(c(tempIdx2, tempIdx1[pVec <= level]))
    }

    if (length(tempIdx2) == 0) {
      attr(geneStart, "change") <- FALSE
      geneEndList[[k]] <- geneStart
      k <- k + 1
    } else {
      for (j in seq_along(tempIdx2)) {
        geneEnd <- c(geneStart, geneCandidate[tempIdx2[j]])
        attr(geneEnd, "S") <- S1Vec[tempIdx2[j]]
        attr(geneEnd, "q") <- q1Vec[tempIdx2[j]]
        attr(geneEnd, "change") <- TRUE
        geneEndList[[k]] <- geneEnd
        k <- k + 1
      }
    }
  }

  geneEndList
}

#' @rdname megsa_search
#' @export
funDrop1RealData <- function(geneStartList, mutationMat, maxSSimu,
                             eps = 0.005, level = 0.05, nPerm = 1e2,
                             permResult = list(), detail = TRUE) {
  mutationMat <- normalize_mutation_matrix(mutationMat)
  maxSSimu <- normalize_max_simu_matrix(maxSSimu)
  minSize <- 2
  geneAll <- colnames(mutationMat)
  N <- nrow(mutationMat)
  geneEndList <- list()
  k <- 1

  for (i in seq_along(geneStartList)) {
    geneStart <- geneStartList[[i]]
    n0 <- length(geneStart)
    if (is.null(attr(geneStart, "S")) || is.null(attr(geneStart, "q"))) {
      tempS <- funEstimate(mutationMat[, geneStart, drop = FALSE])$S
      tempQ <- mean(maxSSimu[, n0 - 1] >= tempS)
      attr(geneStart, "S") <- tempS
      attr(geneStart, "q") <- tempQ
    }
    if (n0 == minSize) {
      attr(geneStart, "change") <- FALSE
    }
    if (!is.null(attr(geneStart, "change")) && !attr(geneStart, "change")) {
      geneEndList[[k]] <- geneStart
      k <- k + 1
      next
    }

    S0 <- attr(geneStart, "S")
    q0 <- attr(geneStart, "q")
    S1Vec <- q1Vec <- rep(NA_real_, n0)
    for (j in seq_len(n0)) {
      S1Vec[j] <- funEstimate(mutationMat[, geneStart[-j], drop = FALSE])$S
      q1Vec[j] <- mean(maxSSimu[, n0 - 2] >= S1Vec[j])
      if (detail) {
        cat(i, j, geneStart, S0, q0, "-", geneStart[j], S1Vec[j], q1Vec[j], "\n")
      }
    }

    tempIdx1 <- which(abs(q1Vec - q0) < eps)
    tempIdx2 <- which(q1Vec <= q0 - eps)
    if (length(tempIdx1) > 0) {
      pVec <- rep(NA_real_, length(tempIdx1))
      for (j in seq_along(tempIdx1)) {
        tempName <- paste(sort(geneStart[-tempIdx1[j]]), collapse = "_")
        if (!is.null(permResult[[tempName]]) && length(permResult[[tempName]]) >= nPerm) {
          pVec[j] <- mean(permResult[[tempName]] >= S0, na.rm = TRUE)
        } else {
          geneCandidate <- geneAll[!geneAll %in% geneStart[-tempIdx1[j]]]
          n1 <- length(geneCandidate)
          maxSPermVec <- rep(NA_real_, nPerm)
          for (ii in seq_len(nPerm)) {
            tempPermIdx <- sample.int(N)
            SPerm <- rep(NA_real_, n1)
            for (jj in seq_len(n1)) {
              APerm <- mutationMat[, c(geneStart[-tempIdx1[j]], geneCandidate[jj]), drop = FALSE]
              APerm[, n0] <- APerm[tempPermIdx, n0]
              SPerm[jj] <- funEstimate(APerm)$S
            }
            maxSPermVec[ii] <- max(SPerm)
            p <- mean(maxSPermVec >= S0, na.rm = TRUE)
            if (ii >= nPerm / 5 && p > 2 * level) {
              break
            }
          }
          pVec[j] <- p
          permResult[[tempName]] <- c(permResult[[tempName]], maxSPermVec[!is.na(maxSPermVec)])
        }
      }
      tempIdx2 <- sort(c(tempIdx2, tempIdx1[pVec > level]))
    }

    if (length(tempIdx2) == 0) {
      attr(geneStart, "change") <- FALSE
      geneEndList[[k]] <- geneStart
      k <- k + 1
    } else {
      for (j in seq_along(tempIdx2)) {
        geneEnd <- geneStart[-tempIdx2[j]]
        attr(geneEnd, "S") <- S1Vec[tempIdx2[j]]
        attr(geneEnd, "q") <- q1Vec[tempIdx2[j]]
        attr(geneEnd, "change") <- n0 > 3
        geneEndList[[k]] <- geneEnd
        k <- k + 1
      }
    }
  }

  attr(geneEndList, "permResult") <- permResult
  geneEndList
}

#' @rdname megsa_search
#' @export
funSelect <- function(mutationMat, maxSSimu = NULL, nSimu = 1000,
                      nPairStart = 10, maxSize = 6, level = 0.05,
                      detail = TRUE, search = c("screened", "exhaustive"),
                      ncores = 1, seed = NULL) {
  search <- match.arg(search)
  mutationMat <- normalize_mutation_matrix(mutationMat)
  test <- funGlobalTest(
    mutationMat,
    maxSSimu = maxSSimu,
    nSimu = nSimu,
    nPairStart = nPairStart,
    maxSize = maxSize,
    detail = detail,
    search = search,
    ncores = ncores,
    seed = seed
  )
  maxSSimu <- test$maxSSimu
  maxSize <- ncol(maxSSimu) + 1
  nPairStart <- ncol(test$startPairIdx)
  geneAll <- colnames(mutationMat)

  if (test$p > level) {
    MEGSList <- list()
  } else {
    MEGSList <- vector("list", nPairStart)
    for (i in seq_len(nPairStart)) {
      tempGeneSet <- geneAll[test$startPairIdx[, i]]
      attr(tempGeneSet, "S") <- test$startPairS[i]
      attr(tempGeneSet, "q") <- mean(maxSSimu[, 1] >= test$startPairS[i])
      attr(tempGeneSet, "change") <- TRUE
      MEGSList[[i]] <- tempGeneSet
    }

    if (maxSize > 2) {
      for (i in seq.int(2, maxSize - 1)) {
        MEGSList <- funAdd1RealData(MEGSList, mutationMat, maxSSimu, detail = detail)
        MEGSList <- deduplicate_gene_sets(MEGSList)
      }
    }

    permResult <- list()
    if (maxSize >= 3) {
      for (i in seq.int(maxSize, 3)) {
        MEGSList <- funDrop1RealData(
          MEGSList,
          mutationMat,
          maxSSimu,
          detail = detail,
          permResult = permResult
        )
        permResult <- attr(MEGSList, "permResult")
        MEGSList <- deduplicate_gene_sets(MEGSList)
      }
    }

    if (length(MEGSList) > 0) {
      MEGSList <- lapply(MEGSList, function(x) {
        attr(x, "pNominal") <- 0.5 * stats::pchisq(attr(x, "S"), 1, lower.tail = FALSE)
        attr(x, "pCorrected") <- mean(test$q <= attr(x, "q"))
        attr(x, "coverage") <- mean(rowSums(mutationMat[, x, drop = FALSE]) > 0)
        attr(x, "q") <- NULL
        attr(x, "change") <- NULL
        x
      })
      correctedP <- vapply(MEGSList, attr, numeric(1), which = "pCorrected")
      MEGSList <- MEGSList[order(correctedP)]
      MEGSList <- MEGSList[correctedP[order(correctedP)] <= level]
    }
  }

  list(p = test$p, MEGSList = MEGSList)
}

#' Format, write, and plot MEGSA results
#'
#' @param MEGSList A list of mutually exclusive gene sets returned by MEGSA.
#' @param outputFile Optional output path for [funPrintMEGS()].
#' @param mutationMat Mutation matrix used by plotting functions.
#' @param outputDir Output directory for [funPlotMEGS()].
#' @param main Optional plot title.
#' @param reorder If `TRUE`, reorder rows and columns in the mutation matrix.
#' @param type Figure file type: `"pdf"`, `"png"`, or `"jpg"`.
#'
#' @return [funPrintMEGS()] returns a data frame. [funPlotMEGS()] invisibly
#'   returns generated file paths.
#'
#' @name megsa_output
NULL

#' @rdname megsa_output
#' @export
funPrintMEGS <- function(MEGSList, outputFile = NULL) {
  if (length(MEGSList) == 0) {
    MEGSDF <- data.frame(
      gene = character(),
      coverage = numeric(),
      LRT = numeric(),
      pNominal = numeric(),
      pCorrected = numeric()
    )
  } else {
    gene <- vapply(MEGSList, paste, character(1), collapse = " ")
    LRT <- vapply(MEGSList, attr, numeric(1), which = "S")
    pNominal <- vapply(MEGSList, attr, numeric(1), which = "pNominal")
    pCorrected <- vapply(MEGSList, attr, numeric(1), which = "pCorrected")
    coverage <- vapply(MEGSList, attr, numeric(1), which = "coverage")
    MEGSDF <- data.frame(
      gene = gene,
      coverage = coverage,
      LRT = LRT,
      pNominal = pNominal,
      pCorrected = pCorrected,
      row.names = NULL
    )
  }

  if (!is.null(outputFile)) {
    utils::write.table(MEGSDF, file = outputFile, sep = "\t", quote = FALSE, row.names = FALSE)
  }
  MEGSDF
}

#' @rdname megsa_output
#' @export
funPlotMutationMat <- function(mutationMat, main = NULL, reorder = TRUE) {
  mutationMat <- normalize_mutation_matrix(mutationMat, min_cols = 1)
  N <- nrow(mutationMat)
  M <- ncol(mutationMat)
  if (reorder) {
    mutationMat <- mutationMat[, order(colSums(mutationMat), decreasing = TRUE), drop = FALSE]
    for (i in rev(seq_len(ncol(mutationMat)))) {
      mutationMat <- mutationMat[order(mutationMat[, i]), , drop = FALSE]
    }
  }

  graphics::image(
    seq_len(M),
    0:N,
    t(!mutationMat),
    axes = FALSE,
    xlim = c(0.5, M + 0.5),
    ylim = c(0, N),
    main = main,
    xlab = "",
    ylab = ""
  )
  graphics::abline(v = 0:M + 0.5, h = c(0, N))
  graphics::axis(1, seq_len(M), colnames(mutationMat))
  graphics::axis(2)
  invisible(mutationMat)
}

#' @rdname megsa_output
#' @export
funPlotMEGS <- function(MEGSList, mutationMat, outputDir, type = c("pdf", "png", "jpg")) {
  type <- match.arg(type)
  mutationMat <- normalize_mutation_matrix(mutationMat)
  if (!dir.exists(outputDir)) {
    dir.create(outputDir, recursive = TRUE)
  }
  if (length(MEGSList) == 0) {
    return(invisible(character()))
  }

  outputFiles <- file.path(outputDir, paste0("gene_set_", seq_along(MEGSList), ".", type))
  for (i in seq_along(MEGSList)) {
    if (type == "pdf") {
      grDevices::pdf(outputFiles[i], width = 5, height = 10)
    } else if (type == "png") {
      grDevices::png(outputFiles[i], width = 600, height = 1200)
    } else {
      grDevices::jpeg(outputFiles[i], width = 600, height = 1200)
    }
    graphics::par(cex.main = 1.5, cex.axis = 1.2)
    funPlotMutationMat(
      mutationMat[, MEGSList[[i]], drop = FALSE],
      main = paste0(
        "Coverage = ", signif(attr(MEGSList[[i]], "coverage"), 3),
        "\nCorrected p = ", signif(attr(MEGSList[[i]], "pCorrected"), 3)
      )
    )
    grDevices::dev.off()
  }

  invisible(outputFiles)
}

#' @rdname megsa_output
#' @export
plot_megs <- funPlotMEGS

#' Historical file-based MEGSA wrapper
#'
#' @inheritParams megsa_file
#'
#' @return A MEGSA result object.
#'
#' @export
funMEGSA <- function(mutationMatFile, maxSSimuFile = NULL, resultTableFile = NULL,
                     figureDir = NULL, nSimu = 1000, nPairStart = 10,
                     maxSize = 6, level = 0.05, detail = TRUE,
                     type = "pdf", search = c("screened", "exhaustive"),
                     ncores = 1, seed = NULL) {
  megsa_file(
    mutationMatFile = mutationMatFile,
    maxSSimuFile = maxSSimuFile,
    resultTableFile = resultTableFile,
    figureDir = figureDir,
    nSimu = nSimu,
    nPairStart = nPairStart,
    maxSize = maxSize,
    level = level,
    detail = detail,
    type = type,
    search = search,
    ncores = ncores,
    seed = seed
  )
}

normalize_mutation_matrix <- function(mutationMat, min_cols = 2) {
  if (is.data.frame(mutationMat)) {
    mutationMat <- as.matrix(mutationMat)
  }
  if (!is.matrix(mutationMat)) {
    stop("mutationMat must be a matrix or data frame.", call. = FALSE)
  }
  if (anyNA(mutationMat)) {
    stop("mutationMat cannot contain missing values.", call. = FALSE)
  }
  if (!is.logical(mutationMat) && !is.numeric(mutationMat) && !is.integer(mutationMat)) {
    stop("mutationMat must contain logical or numeric values.", call. = FALSE)
  }
  mutationMat <- mutationMat != 0
  if (nrow(mutationMat) < 1) {
    stop("mutationMat must contain at least one sample.", call. = FALSE)
  }
  if (ncol(mutationMat) < min_cols) {
    stop("mutationMat must contain at least ", min_cols, " gene columns.", call. = FALSE)
  }
  if (is.null(colnames(mutationMat))) {
    colnames(mutationMat) <- paste0("G", seq_len(ncol(mutationMat)))
  }
  if (anyDuplicated(colnames(mutationMat))) {
    stop("mutationMat column names must be unique.", call. = FALSE)
  }
  mutationMat
}

normalize_max_simu_matrix <- function(maxSSimu) {
  if (is.null(maxSSimu)) {
    return(NULL)
  }
  if (is.data.frame(maxSSimu)) {
    maxSSimu <- as.matrix(maxSSimu)
  }
  if (!is.matrix(maxSSimu)) {
    maxSSimu <- matrix(maxSSimu, ncol = 1)
  }
  storage.mode(maxSSimu) <- "numeric"
  if (anyNA(maxSSimu)) {
    stop("maxSSimu must contain only numeric values.", call. = FALSE)
  }
  if (nrow(maxSSimu) < 1 || ncol(maxSSimu) < 1) {
    stop("maxSSimu must have at least one row and one column.", call. = FALSE)
  }
  maxSSimu
}

estimate_context <- function(mutationMat) {
  N <- nrow(mutationMat)
  M <- ncol(mutationMat)
  row_sums <- rowSums(mutationMat)
  pi_hat <- colMeans(mutationMat)
  gene_counts <- colSums(mutationMat)
  absent_counts <- N - gene_counts
  present_log <- numeric(M)
  absent_log <- numeric(M)
  has_mutations <- gene_counts > 0
  has_absent <- absent_counts > 0
  present_log[has_mutations] <- gene_counts[has_mutations] * log(pi_hat[has_mutations])
  absent_log[has_absent] <- absent_counts[has_absent] * log1p(-pi_hat[has_absent])

  list(
    mutationMat = mutationMat,
    N = N,
    M = M,
    row_sums = row_sums,
    q = as.vector(table(factor(row_sums, levels = 0:M))),
    pi = pi_hat,
    logL0 = sum(present_log + absent_log),
    patterns = mutation_patterns(M),
    row_index = row_pattern_index(mutationMat)
  )
}

context_log_likelihood <- function(parVec, context) {
  gamma <- parVec[1]
  delta <- parVec[-1]
  M <- context$M
  q <- context$q

  if (length(delta) == 1) {
    J <- seq_len(M)
    logL <- M * q[1] * log(1 - delta) + q[1] * log(1 - gamma) +
      sum(q[-1] * (
        log(J / M) + (J - 1) * log(delta) + (M - J) * log(1 - delta) +
          log(M / J * delta * (1 - gamma) + gamma)
      ))
  } else if (length(delta) == M) {
    tempA <- context$patterns
    nPattern <- nrow(tempA)
    tempProbMat <- matrix(delta, nPattern, M, byrow = TRUE)
    tempProbMat[!tempA] <- 1 - tempProbMat[!tempA]
    tempProd <- apply(tempProbMat, 1, prod)
    tempMat <- rep(delta / sum(delta), each = nPattern) * tempA * (tempProd / tempProbMat)
    tempProb <- (1 - gamma) * tempProd + gamma * rowSums(tempMat)
    prob <- tempProb[context$row_index]
    logL <- sum(log(prob))
  } else {
    stop("Invalid value of delta.", call. = FALSE)
  }

  -logL
}

context_gradient <- function(parVec, context) {
  gamma <- parVec[1]
  delta <- parVec[-1]
  M <- context$M
  if (length(delta) == 1) {
    delta <- rep(delta, M)
  }
  if (length(delta) != M) {
    stop("Invalid value of delta.", call. = FALSE)
  }

  sumDelta <- sum(delta)
  tempA <- context$patterns
  nPattern <- nrow(tempA)
  tempProbMat1 <- tempProbMat2 <- matrix(delta, nPattern, M, byrow = TRUE)
  tempProbMat2[!tempA] <- 1 - tempProbMat1[!tempA]
  temp1 <- apply(tempProbMat2, 1, prod)
  temp2 <- temp1 / tempProbMat2
  tempProbMat3 <- tempProbMat1 / sumDelta * tempA * temp2
  temp3 <- rowSums(tempProbMat3)
  tempProb <- (1 - gamma) * temp1 + gamma * temp3
  tempGradGamma <- (temp3 - temp1) / tempProb
  tempGradMat <- matrix(NA_real_, nPattern, M)
  temp4 <- (1 - gamma) * (tempA * 2 - 1) * temp2
  temp5 <- (sumDelta - delta) / sumDelta^2
  temp6 <- rep(temp5, each = nPattern) * tempA * temp2
  for (i in seq_len(M)) {
    temp7 <- -tempProbMat1[, -i, drop = FALSE] / sumDelta^2 *
      tempA[, -i, drop = FALSE] * temp2[, -i, drop = FALSE] +
      tempProbMat1[, -i, drop = FALSE] / sumDelta *
        tempA[, -i, drop = FALSE] *
        (temp2[, -i, drop = FALSE] / tempProbMat2[, i] * (tempA[, i] * 2 - 1))
    tempGradMat[, i] <- temp4[, i] + gamma * (temp6[, i] + rowSums(temp7))
  }
  tempGradMat <- tempGradMat / tempProb
  tempIdx <- context$row_index
  grad <- c(sum(tempGradGamma[tempIdx]), colSums(tempGradMat[tempIdx, , drop = FALSE]))

  -grad
}

mutation_patterns <- local({
  cache <- new.env(parent = emptyenv())

  function(M) {
    key <- as.character(M)
    if (exists(key, envir = cache, inherits = FALSE)) {
      return(get(key, envir = cache, inherits = FALSE))
    }

    tempA <- matrix(FALSE, 2^M, M)
    for (i in seq_len(M)) {
      tempA[, i] <- rep(rep(c(FALSE, TRUE), each = 2^(M - i)), 2^(i - 1))
    }
    assign(key, tempA, envir = cache)
    tempA
  }
})

row_pattern_index <- function(mutationMat) {
  as.integer(colSums(t(mutationMat) * 2^((ncol(mutationMat) - 1):0)) + 1)
}

candidate_add_order <- function(mutationMat, geneStart, geneCandidate, search,
                                corMat = NULL) {
  M1 <- length(geneCandidate)
  if (search == "exhaustive") {
    return(seq_len(M1))
  }
  if (is.null(corMat)) {
    corMat <- safe_cor(mutationMat)
  }
  tempMat <- corMat[geneStart, geneCandidate, drop = FALSE]
  tempVec <- colSums(tempMat / (1 - tempMat^2))
  seq_len(M1)[utils::head(order(tempVec, na.last = TRUE), min(max(floor(M1 * 0.1), 5), M1))]
}

candidate_pair_order <- function(mutationMat, nPairStart, search, corMat = NULL) {
  M <- ncol(mutationMat)
  nPair <- choose(M, 2)
  if (search == "exhaustive") {
    return(seq_len(nPair))
  }
  if (is.null(corMat)) {
    corMat <- safe_cor(mutationMat)
  }
  corVec <- corMat[lower.tri(corMat)]
  seq_len(nPair)[utils::head(order(corVec, na.last = TRUE), min(nPairStart * 5, nPair))]
}

safe_cor <- function(mutationMat) {
  corMat <- suppressWarnings(stats::cor(mutationMat))
  corMat[is.na(corMat)] <- 0
  corMat
}

deduplicate_gene_sets <- function(geneSetList) {
  if (length(geneSetList) == 0) {
    return(geneSetList)
  }
  keys <- vapply(geneSetList, function(x) paste(sort(x), collapse = "_"), character(1))
  geneSetList[!duplicated(keys)]
}

validate_positive_integer <- function(x, name) {
  if (length(x) != 1 || is.na(x) || x < 1 || x != as.integer(x)) {
    stop(name, " must be a positive integer.", call. = FALSE)
  }
  invisible(TRUE)
}
